name: Build and Release Pocket Launcher
on:
  workflow_dispatch: # Adiciona o botão manual na aba Actions
  push:
    branches: [ main ] # Roda sempre que você salvar um arquivo novo

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Baixar Gradle Motor
        run: |
          curl -L https://raw.githubusercontent.com/android/architecture-samples/main/gradlew -o gradlew
          chmod +x gradlew

      - name: Compilar APK (32-bits A13)
        run: ./gradlew assembleDebug

      - name: Criar Release Automática
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0
          name: "Pocket Launcher v1.0"
          body: "Lançador compilado com sucesso para Samsung A13."
          files: app/build/outputs/apk/debug/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
